[server]
headless = true
port = 8600
enableCORS = false

[theme]
base = "light"
primaryColor = "#2E86C1"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[browser]
gatherUsageStats = false
serverAddress = "localhost"

[client]
showErrorDetails = true
toolbarMode = "minimal" 